version: '3.8'

services:
  app:
    build: ./app
    volumes:
      - ./app/:/usr/src/app
    environment:
      - ACCOUNT_ID=${SPOTIFY_ACCOUNT_ID}
      - CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - REFRESH_TOKEN=${SPOTIFY_REFRESH_TOKEN}
      - PYTHONPATH="${PYTHONPATH}:/usr/src/app/spotify_crud"
    ports:
      - 5000:5000
  db:
    volumes:
      - ./db/ddl:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${RANDOM_PASS}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=spotify
    ports:
      - "5432:5432"